### ISSUE TITLE
Enhancement[Icon libarary component]: Icon cards & icon search/filter bar

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website-archive#1094]
Sketchfile: https://ibm.box.com/s/rbrjv9hn9n8nia85z5f69tbt2ijazg2t
Video prototype: https://ibm.box.com/s/817f0vklb47nt4sg5f2mgwnchf8tkruy

YML file of data metadata: https://github.com/IBM/carbon-elements/blob/2d6bdaf676494e10e42f7ae0c8377b25d96330ec/packages/icons/metadata.yml

# Final icon/library page

### Default view of library with icon hover state, and dropdowns expanded
![Icon_Library](https://user-images.githubusercontent.com/15144993/54225151-100e5200-44c9-11e9-85c5-5ed7c11ef430.png)

### icon selected state
![Icon_Library expanded](https://user-images.githubusercontent.com/15144993/54225138-08e74400-44c9-11e9-81d3-798f678f5d9d.png)

### filtered state 
![icon_library filtered](https://user-images.githubusercontent.com/15144993/53374552-46bb6880-391e-11e9-95bc-fc473e8aa6a9.png)

### empty state
![icon_library empty state](https://user-images.githubusercontent.com/15144993/53374558-49b65900-391e-11e9-93fd-ec41e8cf0e46.png)

### mobile
![image](https://user-images.githubusercontent.com/15144993/54226076-04238f80-44cb-11e9-8827-dc31b826977d.png)

# Responsiveness

![image](https://user-images.githubusercontent.com/15144993/53374197-4e2e4200-391d-11e9-938d-3dc579a9b36b.png)

# Spec

![Icon page components](https://user-images.githubusercontent.com/15144993/54226018-e6eec100-44ca-11e9-8a4e-3860f4184477.png)

**Comment by shixiedesign** [comment]
**Will add empty state design soon**

![image](https://user-images.githubusercontent.com/15144993/52662130-2f658f80-2ec9-11e9-96d4-a96cb92a71cf.png)

**Comment by shixiedesign** [comment]
Empty state! 
![icon_library view 2 copy](https://user-images.githubusercontent.com/15144993/52664284-40fd6600-2ece-11e9-8dd3-20d24c9dcb05.png)

**Comment by mjabbink** [comment]
@shixiedesign @jeanservaas 
I think the spacing between Categories is too much. 80 seems excessive. The Dl site seems good or it can be slightly more open maybe.

**Comment by shixiedesign** [comment]
@mjabbink okay. I will make an update today!

**Comment by shixiedesign** [comment]
# Icon page spacing update
![icon_library view 1](https://user-images.githubusercontent.com/15144993/52818863-77251c00-306d-11e9-8b32-6b19630bd123.png)

**Comment by shixiedesign** [comment]
make sure to address search bar buggy behavior described here https://github.com/carbon-design-system/carbon-website/issues/1132

**Comment by joshblack** [comment]
Some developer notes that could be helpful for that use-case/user archetype:

### Importing an icon

The primary way a developer will include an icon is through one of our icon packages. These include:

- `@carbon/icons`
- `@carbon/icons-react`
- `@carbon/icons-angular`
- `@carbon/icons-vue`

Each project contains all of the icons available in Carbon Elements with a consistent name and import path. This means that if you want to import an icon, say `AddFilled16`, one would write the following in each framework:

```js
import AddFilled16 from '@carbon/icons/es/add--filled/16';
import AddFilled16 from '@carbon/icons-react/es/add--filled/16';
import AddFilled16 from '@carbon/icons-angular/es/add--filled/16';
import AddFilled16 from '@carbon/icons-vue/es/add--filled/16';
```

However, the module name and the path to import it can be confusing or hard to discover. For example, how would one know that `AddFilled16` translates to `add--filled/16`. It would be helpful if this information was presented in a way such that a developer could understand how to include an icon resource in their corresponding tool chain 👍 

With respect to the paths themselves, the folder name `es` could be one of the following:

- `es` used for ECMAScript modules (ESM), latest and greatest syntax for code in JavaScript, requires specific settings to use
- `lib` used for CommonJS modules, commonly used as an interop layer. Works in most use-cases
- `umd` used for Universal Module Definitions, used as an interop layer, works in all use cases but suffers from code size/bloat as a result

As a result, the following would be options depending on the developer and their setup:

```js
import AddFilled16 from '@carbon/icons/es/add--filled/16';
import AddFilled16 from '@carbon/icons/lib/add--filled/16';
import AddFilled16 from '@carbon/icons/umd/add--filled/16';
```

**Comment by shixiedesign** [comment]
### Current design for icon expansion panel: 
Spec & sketchfile coming soon.

![image](https://user-images.githubusercontent.com/15144993/53361794-34c9cd80-38fe-11e9-8891-48c24bc0b5f7.png)

**Comment by shixiedesign** [comment]
- [ ] A few more design update coming in via Mike
- [ ] Mobile experience

**Comment by alisonjoseph** [comment]
from Ryan

> the work i did on iconography page is on the branch `iconography-functionality`

> note, the first 3 icons are the only ones that work because i didn't want to write out 700 pieces of dummy data
> AddFilled, AddOutline, Add work. when the drawer is open, you can click the related icons, and click the related search items (edited)

**Comment by mjabbink** [comment]
@alisonjoseph @jeanservaas  Let’s remove cards from Icon Library page as per Jeannie’s comment  in #1284.

**Comment by chrisconnors-ibm** [comment]
@mjabbink @shixiedesign @alisonjoseph @jeanservaas This spec as delivered represents a wedding cake; we still need to see a plan for the cake that lies somewhere between this and where we are right now.

**Comment by chrisconnors-ibm** [comment]
(commenting here bc #1284 is closed.)

@mjabbink @jeanservaas @shixiedesign please keep in mind a couple of important points:

1) Just to re-iterate, we ~do not want to~ **cannot** present people a _frictionless_ path in the Library page to download individual, or groups of individual, icons either for their Sketch design documents or their code for their products. Downloading individual SVGs for use in design documents or god forbid hosting in a product's endpoint orphans them, so they will never get any asset updates as we make them. 

2) The most likely _desired/supported_ reason to download an asset's SVG directly is to edit it or use it as the basis for the creation of a new assets (hopefully for submission). So people can still go to the linked repo and get them there - it's just not how we will instruct or directly enable from the Icon Library page.

3) The reason the asset cards are on the Library page is that the most common reason to go there is not to figure out what icons we have according to synonym or size, but to get them for use. The sources we provide for that are the sketch library that contains them or, for development, the way to use them from the carbon elements package.

If the cards themselves don't work for folks at the top of the page, **please let's figure out an resource download embodiment that does,** perhaps a half height card for example? Simply moving the cards to the end of the page is probably the same as removing them, given the length of that page.

**Comment by jeanservaas** [comment]
@chrisconnors-ibm i totally get what you're saying, but what about people who don't have Sketch?

**Comment by mjabbink** [comment]
Also not bottom of long page but the results of filtering or search. It would make the cards right under the icon/s one searched for. 

But to your point. Why did we add this to library if you can download the whole master Ai file from the repo? I know Conrad is working on a final master. This eliminates the need for this pattern.

Orinally we had ‘copy’ as the only functionality per icon. Can we not go back to that?

@jeannie I think the non Sketch users (there are many) can download the master and get them all!

**Comment by chrisconnors-ibm** [comment]
An Illustrator Master is generally not used  in service of design/spec docs, but in any case should be generated out of what is in carbon-elements Icon package programmatically, as our carbon-elements sketch library will be soon.

The problem with assets (illustrator, sketch, adobe XD etc.) created by hand is they have to be maintained and kept in sync by hand, which is already probably impossible given that our 32x32 SVG asset count alone is 645 individual svg files.

But the thing we need to keep front of mind is that when @Conrad and I or @mjabbink and I and @jeanservaas decide some specific icon is janky, we only need to change it in its repo, and then the sketch library updates, and its symbol is updated, and design docs using that symbol are updated, and built applications already shipped that use the package path to that asset get updated, etc.

**Comment by mjabbink** [comment]
Can we generate Ai file with the whole lot programmatically? That would be awesome. I’d be cool with this but there are a lot of users not using Sketch that may need the icons and one by one downloads won’t be great. Can the repo download the master folder with all svgs in it?

Also the Ai master is nice for anyone also creating some new ones.

Hmm

**Comment by chrisconnors-ibm** [comment]
I don't know if generating an Adobe Illustrator master file based on repo contents is possible, but that's what we're investigating on the Sketch kit side. If we could generate a master .ai file from those contents, it gets us closer to the single source of truth we're generally striving for.

the 'creating new ones' is interesting in that it doesn't have the same requirement to pick up future changes behaviors that we want in our Sketch doc creation or our production environments.

**Comment by alisonjoseph** [comment]
re-opening -- need clarity around what functionality should be limited on IDL site
