### ISSUE TITLE
Write website documentation

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website-archive#20]

**Comment by shinytoyrobots** [comment]
Is this arguably an epic?

**Comment by alisonjoseph** [comment]
This is related to docs on how to contribute content to the website, so expanding on readme and content docs.

https://github.com/carbon-design-system/carbon-website-gatsby/blob/master/README.md
https://github.com/carbon-design-system/carbon-website-gatsby/blob/master/CONTENT.md

**Comment by shinytoyrobots** [comment]
Yeah, I just realized. This is documentation *about* the website, rather than documentation to go on the website, right?

**Comment by alisonjoseph** [comment]
yep!
