### ISSUE TITLE
Carbon X Website: Leadspace Consolidation

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website-archive#548]
Got buy in at the design crit yesterday to align the Carbon leadspaces with digital and IDL leadspaces:

**Leadspace Geometry**
- [x] We already have leadspace geometries aligned: IDL, digital and Carbon have already agreed on the proportions — there is a large, a medium and a small leadspace (dev has already implemented this)

**Leadspace Guidance**

- [x] The homepage is the only page that is allowed to use a large leadspace; no internal pages use it
- [x] Use Medium leadspace for all content in the Guidelines category
- [x] Remove section head from Medium leadspace and put intro paragraph back in (see example and leadspace library below)
- [x] Use Small leadspace for ALL other content on the Carbon site; the small leadspace has no copy other than the Title (i.e. no section head and no paragraph — see examples below)

**Examples**

*Medium leadspace (Guidelines Section Only)*

-Accessibility
-Content
-Color
-Grid
-Iconography
-Layer
-Motion
-Spacing
-Themes
-Typography

![Medium_leadspace.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/d79cc245-dd38-4b6d-863d-a7733ac3c266)

<br>

*Small leadspace (Everywhere else)*

![Small_leadspace.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/19dac6f0-aaeb-4cf6-b7b5-043a45ba8fa0)

**Comment by alisonjoseph** [comment]
@jeanservaas what are the pixel heights for the small and medium lead space? Carbon site is currently `329px` (not sure where we got that number from)

**Comment by shixiedesign** [comment]
**Leadspace heights: @alisonjoseph ** 
large: 512px
medium: 320px
small: 240px
